version: "2"
services:
    www:
        build: .
        networks:
            - default
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public/
    db:
        image: mariadb:10.4
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: carcoop
            MYSQL_USER: carcoop
            MYSQL_PASSWORD: carcoop
            MYSQL_ROOT_PASSWORD: carcoop
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: carcoop
            MYSQL_PASSWORD: carcoop
            MYSQL_ROOT_PASSWORD: carcoop
        logging:
            driver: none
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        logging:
            driver: none

volumes:
    persistent:
