[program:car-coop-messenger]
command=php /var/www/vhosts/car-coop/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
user=www-data
directory=/var/www/vhosts/car-coop
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/car-coop-messenger.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=APP_ENV="prod"
